services:
  - type: web
    name: users-microservice
    runtime: docker
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://YOUR_DB_HOST:3306/authSprinf?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - key: SPRING_DATASOURCE_USERNAME
        value: your_db_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: your_db_password
      - key: SECRET_KEY
        value: ChangeMeSecretKey
      - key: EXPIRATION_TIME
        value: "360000"
      - key: SWAGGER_SERVER_URL
        value: https://users-microservice.onrender.com
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /v3/api-docs
    plan: free

